name: Build

on:
  push:
    branches:
      - main

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: vimtor/action-zip@v1.1
        with:
          files: dist/
          recursive: true
          dest: prompts-repo-build.zip
      - uses: actions/upload-artifact@v1
        with:
          name: prompts-repo-build
          path: ${{ github.workspace }}/prompts-repo-build.zip
      - uses: actions/download-artifact@v3
        with:
          name: prompts-repo-build