name: Build

on:
  push:
    branches:
      - main

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: vimtor/action-zip@v1.1
        with:
          files: dist/
          recursive: true
          dest: prompts-repo.zip